mongodb:
  connection-string: mongodb://config-service:config-service@logginator-storage-cluster-shard-00-00-xmfyu.gcp.mongodb.net:27017,logginator-storage-cluster-shard-00-01-xmfyu.gcp.mongodb.net:27017,logginator-storage-cluster-shard-00-02-xmfyu.gcp.mongodb.net:27017/test?ssl=true&replicaSet=logginator-storage-cluster-shard-0&authSource=admin&retryWrites=true&w=majority
  database-name: config-service

jms:
  broker:
    url: tcp://localhost:61616
    username: admin
    password: admin
  activemq:
    topic-name: config-service.parameters

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

config-provider:
  app-name: config-service
  configs:
    - name: errors
      version: 1.0
      clazz: com.kostylenko.config_service.config_provider.common_config.Message
      beanName: errors
  broker-url: tcp://localhost:61616